hyperledger/indy-test-automation

LICENSE
README.md
chaos/chaosindy/actions/node.py
chaos/chaosindy/common/cli/__init__.py
chaos/chaosindy/common/cli/batch_builder.py
chaos/chaosindy/common/cli/cli_runner.py
chaos/chaosindy/common/cli/commands.py
chaos/chaosindy/common/cli/operations.py
chaos/chaosindy/ledger_interaction.py
chaos/chaosindy/probes/validator_info.py
chaos/scripts/run-consensus-recovery
chaos/scripts/run-demote-promote
chaos/scripts/run-demote-replica
chaos/scripts/run-force-catchup-blocked-port
chaos/scripts/run-force-catchup-service-down
chaos/scripts/run-force-view-change
chaos/scripts/run-replica-selection
chaos/scripts/run-shrink-pool
chaos/scripts/run-view-change-subversion
environments/chaos/README.md
environments/chaos/Vagrantfile
environments/chaos/config.properties.template
environments/chaos/scripts/client.sh
environments/chaos/scripts/validator.sh
environments/chaos/setup

1. indy-test-automation needed an Apache 2.0 license
2. Improvements and refactoring of chaosindy module
3. Provide a chaos development/test environment

chaosindy improvements and initial contribution of a chaos development environment

---

system/conftest.py
system/test_vc.py
system/utils.py

add vc tests and some fixtures

---

system/requirements.txt

add requirements.txt

---

system/indy-sdk-tests/config.json
system/indy-sdk-tests/test_crypto.py
system/indy-sdk-tests/test_pool.py
system/indy-sdk-tests/test_vcx_acceptance.py
system/indy-sdk-tests/test_wallet.py
system/test_freshness.py
system/test_libsovtoken.py
system/test_misc.py
system/test_roles.py

another bunch of additions and updates

---

system/indy-node-tests/test_consensus.py
system/indy-node-tests/test_vc.py
system/indy-node-tests/test_vc_new.py
system/test_upgrade.py
system/utils.py

hotfixes for CD pipeline

---

system/indy-node-tests/test_consensus.py
system/indy-node-tests/test_vc.py
system/test_misc.py
system/utils.py

add fair dids to all tests and fill pool ledger in audit test

---

system/indy-node-tests/test_consensus.py
system/utils.py

fix seed generation and consensus recovery waiting

---

environments/chaos/docker/README.md
environments/chaos/docker/chaos.client.init.dockerfile
environments/chaos/docker/chaos.node.init.dockerfile
environments/chaos/docker/client_build.sh
environments/chaos/docker/client_for_pool_start.sh
environments/chaos/docker/config
environments/chaos/docker/node_build.sh

Signed-off-by: olga.zheregelya <olga.zheregelya@dsr-company.com>

add scripts and dockerfiles for chaos environment

---

system/conftest.py
system/docker/prepare.sh
system/docker/run.sh
system/indy-node-tests/test_vc.py
system/utils.py

- makes logic of write/read checks more accurate
- fixes pytest warning for custom marker
- dumps env of in-docker tests run

[INDY-2131] Test fixtures hardening

---

system/utils.py

fix getting primary time limit

---

system/docker/node/Dockerfile

fix gpg key

---

system/docker/client/Dockerfile

Signed-off-by: Andrew Nikitin <andrew.nikitin@dsr-corporation.com>

[INDY-2163] change gpg key for client's dockerfile

---

system/utils.py

Signed-off-by: Andrew Nikitin <andrew.nikitin@dsr-corporation.com>

[FIX] increase timeout for view change

---

system/indy-node-tests/TestTAASuite.py

Signed-off-by: toktar <renata.toktar@dsr-corporation.com>

INDY-2157: update TAA tests

---

system/indy-node-tests/test_upgrade.py

skip upgrade

---

system/docker/run.sh

Signed-off-by: Andrew Nikitin <andrew.nikitin@dsr-corporation.com>

[ADD LOGGING] add tmp dir mounting

---

system/conftest.py
system/draft/TestProductionSuite.py
system/draft/test_misc.py
system/indy-node-tests/TestCatchUpSuite.py
system/indy-node-tests/TestCatchUpSuiteExtended.py
system/utils.py

add new catchup case and update production case and default retry wait

---

system/operations/ansible_via_python.py
system/operations/indy_config.py
system/operations/indy_config_default.py
system/operations/pool_get_logs.yml
system/operations/pool_install.yml
system/operations/pool_uninstall.yml
system/operations/pool_update_config.yml

move ansible playbooks to system test repository

---

system/indy-node-tests/TestCatchUpSuite.py

fix parameter

---

system/indy-node-tests/TestCatchUpSuite.py
system/indy-node-tests/TestCatchUpSuiteExtended.py

Signed-off-by: ashcherbakov <alexander.sherbakov@dsr-corporation.com>

INDY-2274: fix tests

---

analysis/README.md
analysis/general_metrics.json
analysis/start_database.sh
analysis/stop_database.sh
analysis/upload-logs.py
analysis/upload-metrics.py

Signed-off-by: Sergey Khoroshavin <skhoroshavin@gmail.com>

[PoC] Metrics and logs analysis with InfluxDB and Grafana

---

system/draft/test_misc.py
system/indy-node-tests/TestProductionSuite.py

update tests for CD

---

system/docker_setup.py
system/draft/test_upgrade_docker_7_auth_rule.py
system/draft/test_upgrade_docker_7_mint_xfer.py
system/draft/test_upgrade_docker_7_set_fees.py
system/utils.py

split upgrade cases

---

system/draft/test_misc.py
system/indy-node-tests/test_state_proof.py
system/operations/pool_install.yml

add and update tests and scripts

---

system/docker_setup.py

set debug logging

---

system/indy-node-tests/test_state_proof.py
system/utils.py

fix intermittent timeout failure

---

system/docker_setup.py
system/utils.py

Method wait_until_pool_is_ready didn't work properly on slow machines.

Fixed wait_until_pool_is_ready()

---

system/docker/prepare.sh

Signed-off-by: Devin Smith <devinleighsmith@gmail.com>

Manually include environment variables into node docker build.

---

system_node_only/docker/README.md
system_node_only/docker/run.sh

Signed-off-by: udosson <klemens@internet-sicherheit.de>

improvements of readme and one bug fix when running locally

---

.gitignore
system_node_only/docker/run.sh

This PR creates a `.txt` of the test results in addition to the `junit-xml` report.
Signed-off-by: udosson <klemens@internet-sicherheit.de>

added a .txt output file of the test results

---

.github/workflows/callable_test-automation-extention.yaml
.github/workflows/callable_test-automation-node.yaml
.github/workflows/callable_test-automation.yaml
.github/workflows/dispatchable_test-automation.yaml

- Address warning raised while running workflows.

Upgrade GHA versions

---

system/docker/node/Dockerfile.node

In order to be able to create the node image we must create the config directory

Create the config dir and create and empty file
